project:
  type: website
  output-dir: docs
  resources:
    - presentation.pdf

author: "Add team name here in _quarto.yml"

website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Presentation
        href: presentation.pdf  
      - text: Proposal
        href: proposal.qmd
      - text: About
        href: about.qmd
      - text: Contract
        href: contract.qmd

format:
  html:
    theme: default
